<?php

return [
    'definitions' => [
        'app_name' => [
            'group' => 'general',
            'label' => 'Application Name',
            'type' => 'text',
            'description' => 'Displayed across admin branding and notifications.',
            'default' => 'HOXTAN',
        ],
        'support_email' => [
            'group' => 'general',
            'label' => 'Support Email',
            'type' => 'email',
            'description' => 'Contact email shown to users.',
            'default' => 'support@hoxtan.com',
        ],
        'support_phone' => [
            'group' => 'general',
            'label' => 'Support Phone',
            'type' => 'text',
            'description' => 'Support contact number.',
            'default' => '',
        ],
        'gst_rate_percent' => [
            'group' => 'finance',
            'label' => 'GST Rate (%)',
            'type' => 'number',
            'description' => 'GST percentage applied on buy transactions (split equally as CGST + SGST).',
            'default' => '3',
        ],
        'jewellery_delivery_days' => [
            'group' => 'jewellery',
            'label' => 'Jewellery Delivery Days',
            'type' => 'number',
            'description' => 'Estimated days until jewellery order delivery (from order date).',
            'default' => '10',
        ],
        'metals_api_gold_symbol' => [
            'group' => 'metal_rates',
            'label' => 'Metals-API Gold Symbol (India)',
            'type' => 'text',
            'description' => 'India gold symbol from Metals-API (e.g. VISA-24k, VIJA-22k, SALE-22k). Requires METALS_API_KEY in .env.',
            'default' => 'VISA-24k',
        ],
        'gold_live_api_url' => [
            'group' => 'metal_rates',
            'label' => 'Gold Custom API URL (optional)',
            'type' => 'url',
            'description' => 'Fallback custom URL if Metals-API is unavailable. Leave empty when using Metals-API.',
            'default' => '',
        ],
        'gold_live_api_json_path' => [
            'group' => 'metal_rates',
            'label' => 'Gold JSON Path',
            'type' => 'text',
            'description' => 'Dot-notation path to gold rate in API response (e.g. rates.gold or price).',
            'default' => 'price',
        ],
        'gold_fallback_rate' => [
            'group' => 'metal_rates',
            'label' => 'Gold Fallback Rate (₹/g)',
            'type' => 'number',
            'description' => 'Used when live API is unavailable or not configured.',
            'default' => '7250',
        ],
        'silver_live_api_url' => [
            'group' => 'metal_rates',
            'label' => 'Silver Custom API URL (optional)',
            'type' => 'url',
            'description' => 'Fallback custom URL if Metals-API is unavailable. Leave empty when using Metals-API.',
            'default' => '',
        ],
        'silver_live_api_json_path' => [
            'group' => 'metal_rates',
            'label' => 'Silver JSON Path',
            'type' => 'text',
            'description' => 'Dot-notation path to silver rate in API response.',
            'default' => 'price',
        ],
        'silver_fallback_rate' => [
            'group' => 'metal_rates',
            'label' => 'Silver Fallback Rate (₹/g)',
            'type' => 'number',
            'description' => 'Used when live API is unavailable or not configured.',
            'default' => '85.5',
        ],
        'metal_api_timeout_seconds' => [
            'group' => 'metal_rates',
            'label' => 'API Timeout (seconds)',
            'type' => 'number',
            'description' => 'Maximum wait time when fetching live metal rates.',
            'default' => '10',
        ],
        'metal_api_headers' => [
            'group' => 'metal_rates',
            'label' => 'API Headers (JSON)',
            'type' => 'textarea',
            'description' => 'Optional JSON object for API headers, e.g. {"Authorization":"Bearer token"}.',
            'default' => '{}',
        ],
        'welcome_bonus_enabled' => [
            'group' => 'referrals',
            'label' => 'Welcome Bonus Enabled',
            'type' => 'text',
            'description' => 'Set to 1 to credit new users on registration, 0 to disable.',
            'default' => '1',
        ],
        'welcome_bonus_amount' => [
            'group' => 'referrals',
            'label' => 'Welcome Bonus Amount (₹)',
            'type' => 'number',
            'description' => 'Wallet credit given to every new user on registration.',
            'default' => '50',
        ],
        'referral_bonus_enabled' => [
            'group' => 'referrals',
            'label' => 'Refer & Earn Enabled',
            'type' => 'text',
            'description' => 'Set to 1 to reward referrers when someone registers with their code.',
            'default' => '1',
        ],
        'referral_bonus_amount' => [
            'group' => 'referrals',
            'label' => 'Referral Bonus Amount (₹)',
            'type' => 'number',
            'description' => 'Wallet credit given to the referrer when a new user signs up with their code.',
            'default' => '100',
        ],
        'mpin_length' => [
            'group' => 'referrals',
            'label' => 'MPIN Length (digits)',
            'type' => 'number',
            'description' => 'Number of digits for user MPIN (4 or 6). Used for registration and login.',
            'default' => '4',
        ],
    ],
];
