<?php

/**
 * HOXTAN admin report registry — maps requirement #1–23 to modules and pages.
 * Sub-admins get per-module view/export via config/admin_permissions.php.
 */
return [
    'categories' => [
        'users' => 'User Reports',
        'transactions' => 'Transaction Reports',
        'kyc' => 'KYC & Client Reports',
        'investments' => 'SIG / Metal Reports',
        'jewellery' => 'Jewellery Reports',
        'finance' => 'Finance & GST',
        'operations' => 'Operations & Controls',
    ],

    'category_meta' => [
        'users' => [
            'icon' => 'heroicon-o-users',
            'accent' => 'primary',
            'description' => 'New, active, inactive users and employee referrals.',
        ],
        'transactions' => [
            'icon' => 'heroicon-o-arrows-right-left',
            'accent' => 'info',
            'description' => 'Debit, credit, bonus, referral and wallet movements.',
        ],
        'kyc' => [
            'icon' => 'heroicon-o-identification',
            'accent' => 'warning',
            'description' => 'Client KYC bundles, status and document exports.',
        ],
        'investments' => [
            'icon' => 'heroicon-o-chart-bar-square',
            'accent' => 'success',
            'description' => 'SIG buy/sell, holdings, goals and periodic summaries.',
        ],
        'jewellery' => [
            'icon' => 'heroicon-o-sparkles',
            'accent' => 'danger',
            'description' => 'Jewellery orders, inventory and old gold bookings.',
        ],
        'finance' => [
            'icon' => 'heroicon-o-calculator',
            'accent' => 'gray',
            'description' => 'GST files and tax-related downloads.',
        ],
        'operations' => [
            'icon' => 'heroicon-o-shield-check',
            'accent' => 'primary',
            'description' => 'Account blocks, holds, wallet credit and restrictions.',
        ],
    ],

    'definitions' => [
        'reports_new_users' => [
            'number' => 1,
            'label' => 'New User Reports',
            'description' => 'SIG buy/sell, withdrawal, deposit, wallet, referral bonus, jewellery activity for newly registered users.',
            'category' => 'users',
            'page' => \App\Filament\Pages\Reports\NewUsersReport::class,
            'status' => 'available',
        ],
        'reports_active_investors' => [
            'number' => 2,
            'label' => 'Active Investors',
            'description' => 'Full activity for users with active gold/silver holdings or recent SIG transactions.',
            'category' => 'users',
            'page' => \App\Filament\Pages\Reports\ActiveInvestorsReport::class,
            'status' => 'available',
        ],
        'reports_inactive_users' => [
            'number' => 3,
            'label' => 'Inactive Users History',
            'description' => 'Past transaction and wallet history for users with no recent activity.',
            'category' => 'users',
            'page' => \App\Filament\Pages\Reports\InactiveUsersReport::class,
            'status' => 'available',
        ],
        'reports_transactions' => [
            'number' => 4,
            'label' => 'Transaction Breakdown',
            'description' => 'Debit, credit, withdrawal, processing, bonus, referral paid/pending, GST-linked movements.',
            'category' => 'transactions',
            'page' => \App\Filament\Pages\Reports\TransactionBreakdownReport::class,
            'status' => 'available',
        ],
        'reports_client_kyc' => [
            'number' => 5,
            'label' => 'Client ID & KYC Bundle',
            'description' => 'KYC, Aadhaar, PAN, bank, UPI, face verification and document paths per client.',
            'category' => 'kyc',
            'page' => \App\Filament\Pages\Reports\ClientKycReport::class,
            'status' => 'available',
        ],
        'reports_kyc_status' => [
            'number' => 6,
            'label' => 'KYC Status Reports',
            'description' => 'Verified, pending, failed — PAN, Aadhaar, face, bank pending breakdown.',
            'category' => 'kyc',
            'page' => \App\Filament\Pages\Reports\KycStatusReport::class,
            'status' => 'available',
        ],
        'reports_jewellery' => [
            'number' => 7,
            'label' => 'Jewellery Activity',
            'description' => 'Purchase, cart, failed payment and order status.',
            'category' => 'jewellery',
            'page' => \App\Filament\Pages\Reports\JewelleryActivityReport::class,
            'status' => 'available',
        ],
        'reports_employees' => [
            'number' => 8,
            'label' => 'Employee & Referral IDs',
            'description' => 'Staff user accounts and their referral chain details.',
            'category' => 'users',
            'page' => \App\Filament\Pages\Reports\EmployeeReferralReport::class,
            'status' => 'available',
        ],
        'reports_kyc_documents' => [
            'number' => 9,
            'label' => 'Bulk KYC Documents',
            'description' => 'Export all user KYC document metadata for compliance download.',
            'category' => 'kyc',
            'page' => \App\Filament\Pages\Reports\BulkKycDocumentsReport::class,
            'status' => 'available',
        ],
        'reports_wallet_credit' => [
            'number' => 10,
            'label' => 'Wallet Credit (Direct)',
            'description' => 'Credit client wallet directly — use Wallet → Credit / Debit Management.',
            'category' => 'operations',
            'page' => \App\Filament\Pages\Wallet\CreditDebitManagement::class,
            'status' => 'link',
        ],
        'reports_account_controls' => [
            'number' => 11,
            'label' => 'Block / Hold / Withdrawal Controls',
            'description' => 'Block, hold withdrawal, unblock and connect to HOXTAN support.',
            'category' => 'operations',
            'page' => \App\Filament\Pages\Reports\AccountControlsReport::class,
            'status' => 'available',
        ],
        'reports_account_block' => [
            'number' => 12,
            'label' => 'Full Account Block',
            'description' => 'Block client account — mobile, email, Aadhaar, PAN searchable.',
            'category' => 'operations',
            'page' => \App\Filament\Pages\Reports\AccountBlockReport::class,
            'status' => 'available',
        ],
        'reports_wallet_restrictions' => [
            'number' => 13,
            'label' => 'Wallet / Bonus / Referral Restrictions',
            'description' => 'Partial blocks on wallet balance, bonus and referral earnings.',
            'category' => 'operations',
            'page' => \App\Filament\Pages\Reports\WalletRestrictionsReport::class,
            'status' => 'available',
        ],
        'reports_offers_goals' => [
            'number' => 14,
            'label' => 'Goals & Targeted Offers',
            'description' => 'Investment goals and offers for all users or specific client IDs.',
            'category' => 'investments',
            'page' => \App\Filament\Pages\Reports\GoalsOffersReport::class,
            'status' => 'available',
        ],
        'reports_sig_periodic' => [
            'number' => 15,
            'label' => 'SIG Periodic Reports',
            'description' => 'Daily, weekly, monthly SIG buy/sell aggregates.',
            'category' => 'investments',
            'page' => \App\Filament\Pages\Reports\SigPeriodicReport::class,
            'status' => 'available',
        ],
        'reports_holdings' => [
            'number' => 16,
            'label' => 'Total Holdings',
            'description' => 'Platform-wide and per-user gold/silver holdings.',
            'category' => 'investments',
            'page' => \App\Filament\Pages\Reports\HoldingsReport::class,
            'status' => 'available',
        ],
        'reports_jewellery_total' => [
            'number' => 17,
            'label' => 'Total Jewellery Reports',
            'description' => 'All jewellery orders and revenue summary.',
            'category' => 'jewellery',
            'page' => \App\Filament\Pages\Reports\JewelleryTotalReport::class,
            'status' => 'available',
        ],
        'reports_buy_metal' => [
            'number' => 18,
            'label' => 'Buy Gold / Silver',
            'description' => 'All SIG buy transactions.',
            'category' => 'investments',
            'page' => \App\Filament\Pages\Reports\BuyMetalReport::class,
            'status' => 'available',
        ],
        'reports_sell_withdraw' => [
            'number' => 19,
            'label' => 'Sell & Withdraw',
            'description' => 'SIG sell and physical withdrawal/redemption reports.',
            'category' => 'investments',
            'page' => \App\Filament\Pages\Reports\SellWithdrawReport::class,
            'status' => 'available',
        ],
        'reports_old_gold' => [
            'number' => 20,
            'label' => 'Old Gold Booking',
            'description' => 'Failed, success, processing, completed old gold bookings.',
            'category' => 'jewellery',
            'page' => \App\Filament\Pages\Reports\OldGoldBookingReport::class,
            'status' => 'available',
        ],
        'reports_all_purchases' => [
            'number' => 21,
            'label' => 'All Purchases Download',
            'description' => 'Combined gold, silver and jewellery purchase export.',
            'category' => 'investments',
            'page' => \App\Filament\Pages\Reports\AllPurchasesReport::class,
            'status' => 'available',
        ],
        'reports_gst_file' => [
            'number' => 22,
            'label' => 'GST File (Date Range)',
            'description' => 'Download GST report file from date to date.',
            'category' => 'finance',
            'page' => \App\Filament\Pages\Reports\GstDateRangeReport::class,
            'status' => 'available',
        ],
        'reports_jewellery_inventory' => [
            'number' => 23,
            'label' => 'Jewellery Inventory Status',
            'description' => 'Sold out, coming soon, out of stock catalogue status.',
            'category' => 'jewellery',
            'page' => \App\Filament\Pages\Reports\JewelleryInventoryReport::class,
            'status' => 'available',
        ],
        'reports_legacy' => [
            'number' => 0,
            'label' => 'Legacy Combined Reports',
            'description' => 'Original investment, revenue, user, tax and redemption tabs.',
            'category' => 'finance',
            'page' => \App\Filament\Pages\Reports::class,
            'status' => 'available',
        ],
    ],
];
